const fs = require('fs');

const weedRegex = /window\.canonicalizeWeedSpecies = function[\s\S]*?return next;\s*\};/;
const codeRaw = fs.readFileSync('legacy_script.js', 'utf8');

const match = weedRegex.exec(codeRaw);
if (match) {
    let code = match[0];
    code = code.replace(/window\.canonicalizeWeedSpecies = function/g, 'export function canonicalizeWeedSpecies');
    code = code.replace(/window\.isMixedWeedPlaceholder = function/g, 'export function isMixedWeedPlaceholder');
    code = code.replace(/window\.upsertCoverCorrectionNote = function/g, 'export function upsertCoverCorrectionNote');
    code = code.replace(/window\.getCoverCorrectionValue = function/g, 'export function getCoverCorrectionValue');
    code = code.replace(/window\.isAutoGeneratedWeedEntry = function/g, 'export function isAutoGeneratedWeedEntry');
    code = code.replace(/window\.getWeedBiology = function/g, 'export function getWeedBiology');
    code = code.replace(/window\.getGradedWeedStatus = function/g, 'export function getGradedWeedStatus');
    code = code.replace(/window\.normalizeLifecycleSafeStatus = function/g, 'export function normalizeLifecycleSafeStatus');
    code = code.replace(/window\.getTrialWeedHistory = function/g, 'export function getTrialWeedHistory');
    code = code.replace(/window\.buildWeedTrackingPromptContext = function/g, 'export function buildWeedTrackingPromptContext');
    code = code.replace(/window\.applyHistoricalWeedTracking = function/g, 'export function applyHistoricalWeedTracking');

    code = code.replace(/window\.PERENNIAL_WEEDS = new Set\(\[/g, 'export const PERENNIAL_WEEDS = new Set([');
    code = code.replace(/window\.ANNUAL_WEEDS = new Set\(\[/g, 'export const ANNUAL_WEEDS = new Set([');
    code = code.replace(/window\.SEDGE_WEEDS = new Set\(\[/g, 'export const SEDGE_WEEDS = new Set([');

    code = code.replace(/window\./g, '');
    fs.writeFileSync('src/utils/weedUtils.js', code);
}
