export function canonicalizeWeedSpecies (rawName) {
                const name = String(rawName || '').trim();
                if (!name) return 'Unknown';

                const lower = name.toLowerCase().replace(/\s+/g, ' ');
                const aliasMap = {
                    'bermudagrass': 'Cynodon dactylon',
                    'couch grass': 'Cynodon dactylon',
                    'doob grass': 'Cynodon dactylon',
                    'durva grass': 'Cynodon dactylon',
                    'cynodon dactylon': 'Cynodon dactylon',
                    'ricinus communis': 'Ricinus communis',
                    'castor bean': 'Ricinus communis',
                    'castor': 'Ricinus communis',
                    'broadleaf': 'Broadleaf weed (unidentified)',
                    'broad leaf': 'Broadleaf weed (unidentified)',
                    'broadleaf weed': 'Broadleaf weed (unidentified)',
                    'mixed weeds': 'Mixed weed population',
                    'unidentified weeds (mixed weeds)': 'Mixed weed population',
                    'mixed weed population': 'Mixed weed population',
                    'total': 'Total'
                };

                if (aliasMap[lower]) return aliasMap[lower];
                if (lower.includes('cynodon') || lower.includes('bermuda')) return 'Cynodon dactylon';
                if (lower.includes('broadleaf')) return 'Broadleaf weed (unidentified)';

                return name
                    .split(' ')
                    .filter(Boolean)
                    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
                    .join(' ');
            };

            // Placeholder bucket for unknown baseline composition, not a true species.
            export function isMixedWeedPlaceholder (speciesName) {
                const s = String(speciesName || '').trim().toLowerCase();
                return s === 'mixed weeds' || s === 'mixed weed population' || s === 'unidentified weeds (mixed weeds)';
            };

            // Keep only one canonical cover-correction annotation in notes.
            export function upsertCoverCorrectionNote (notes, message) {
                const base = String(notes || '').replace(/\s*\[Cover corrected:[^\]]*\]/gi, '').trim();
                const suffix = ` [Cover corrected: ${String(message || '').trim()}]`;
                return base ? `${base}${suffix}` : suffix.trim();
            };

            export function getCoverCorrectionValue (notes) {
                const match = String(notes || '').match(/Cover\s*corrected:\s*(\d+(?:\.\d+)?)%/i);
                if (!match) return null;
                const value = parseFloat(match[1]);
                return isFinite(value) ? Math.max(0, Math.min(100, value)) : null;
            };

            export function isAutoGeneratedWeedEntry (wd) {
                if (!wd || typeof wd !== 'object') return false;
                if (wd.autoInjected === true) return true;
                const notes = String(wd.notes || wd.note || '').trim().toLowerCase();
                return notes === 'added from prior observation history for daily species tracking.'
                    || /^(auto-repaired:|auto-added:|auto-tracking:)/i.test(notes);
            };

            // Known perennial weeds - 0% cover may indicate top-kill, not full root elimination
            export const PERENNIAL_WEEDS = new Set([
                'cynodon dactylon', 'cyperus rotundus', 'cyperus esculentus',
                'digitaria abyssinica', 'imperata cylindrica', 'paspalum conjugatum',
                'commelina benghalensis', 'oxalis corniculata', 'convolvulus arvensis',
                'sorghum halepense', 'cirsium arvense', 'equisetum arvense',
                'agropyron repens', 'elytrigia repens', 'rumex crispus',
                'taraxacum officinale', 'plantago major', 'ranunculus repens',
                'trifolium repens', 'pennisetum clandestinum', 'panicum maximum',
                'paspalum dilatatum', 'axonopus compressus', 'stenotaphrum secundatum'
            ]);

            // Minimal biology maps used by the universal weed engine
            export const ANNUAL_WEEDS = new Set([
                'parthenium hysterophorus', 'amaranthus viridis', 'echinochloa colona',
                'digera arvensis', 'trianthema portulacastrum'
            ]);
            export const SEDGE_WEEDS = new Set([
                'cyperus rotundus', 'cyperus esculentus'
            ]);

            // Classify weed biology so logic is lifecycle-driven for any species.
            export function getWeedBiology (speciesName) {
                const s = String(speciesName || '').trim().toLowerCase();
                const perennialSet = PERENNIAL_WEEDS || new Set();
                const annualSet = ANNUAL_WEEDS || new Set();
                const sedgeSet = SEDGE_WEEDS || new Set();
                const type = sedgeSet.has(s)
                    ? 'Sedge'
                    : (/(grass|poa|panicum|digitaria|cynodon|paspalum|sorghum|echinochloa)/i.test(s) ? 'Grass' : 'Broadleaf');
                let lifecycle = 'Unknown';
                if (perennialSet.has(s)) lifecycle = 'Perennial';
                else if (annualSet.has(s)) lifecycle = 'Annual';
                return {
                    type,
                    lifecycle,
                    isPerennial: lifecycle === 'Perennial',
                    regrowthRisk: lifecycle === 'Perennial' || type === 'Sedge'
                };
            };

            /**
             * Graded weed efficacy status based on control % (reduction from baseline).
             * @param {number} controlPct - Control % (0-100). 100 = weed eliminated.
             * @param {boolean} isPerennial - If true, 0% cover ? Top-kill instead of Eliminated.
             * @returns {{ grade: string, label: string }}
             */
            export function getGradedWeedStatus (controlPct, isPerennial, lifecycle = 'Known') {
                if (!isFinite(controlPct) || controlPct < 0) controlPct = 0;
                if (controlPct > 100) controlPct = 100;
                if (lifecycle === 'Unknown' && controlPct >= 100) {
                    return { grade: 'Suppressed', label: 'Control uncertain (unknown lifecycle)' };
                }
                if (controlPct === 100) return { grade: isPerennial ? 'Top-kill' : 'Eliminated', label: '100% control' };
                if (controlPct >= 90)   return { grade: 'Excellent control', label: `${controlPct.toFixed(0)}% control` };
                if (controlPct >= 70)   return { grade: 'Strong control',    label: `${controlPct.toFixed(0)}% control` };
                if (controlPct >= 40)   return { grade: 'Moderate control',  label: `${controlPct.toFixed(0)}% control` };
                if (controlPct >= 20)   return { grade: 'Weak control',      label: `${controlPct.toFixed(0)}% control` };
                return { grade: 'Unaffected', label: controlPct > 0 ? `${controlPct.toFixed(0)}% control` : 'No effect' };
            };

            // Global status safety layer so lifecycle/regrowth rules are enforced consistently.
            export function normalizeLifecycleSafeStatus (speciesName, status, notes = '', prevCover = null, currentCover = null) {
                if (isMixedWeedPlaceholder && isMixedWeedPlaceholder(speciesName)) {
                    return 'Baseline reference';
                }
                const bio = getWeedBiology(speciesName);
                const deadRx = /\b(brown|browning|desiccated|desiccation|wilting|wilted|chlorosis|chlorotic|necrosis|necrotic|dead|dying|burned|burning|scorched|dried|suppressed|suppression|controlled|killed|die-?back|dieback)\b/i;
                const growthRx = /\b(regrowth|re-emerg|re-grow|new\s+growth|new\s+green|seedling|sprouting|emerging|active\s+growth|green\s+shoot)\b/i;

                let next = String(status || '').trim();
                let lower = next.toLowerCase();
                const prev = isFinite(parseFloat(prevCover)) ? (parseFloat(prevCover) || 0) : null;
                const current = isFinite(parseFloat(currentCover)) ? (parseFloat(currentCover) || 0) : null;

                if (lower === 'not detected' && current !== null && current <= 0.1) {
                    return 'Not detected';
                }

                if ((/^auto-repaired:\s*species tracked in other observations/i.test(String(notes || '')) || /^auto-tracking:\s*species tracked in other observations/i.test(String(notes || ''))) &&
                    (prev === null || prev <= 0.1) && current !== null && current <= 0.1) {
                    return 'Not detected';
                }

                // Strict precedence: if cover rebounds above the prior observation, it is regrowth.
                if (prev !== null && current !== null && current > (prev + 0.1) && lower !== 'emerged') {
                    next = 'Regrowth';
                    lower = 'regrowth';
                }

                // Preserve explicit emergence label.
                if (lower === 'emerged') return 'Emerged';

                // Lifecycle-first zero-cover mapping.
                if (current !== null && current <= 0.1) {
                    if (bio.lifecycle === 'Perennial') return 'Top-kill';
                    if (bio.lifecycle === 'Annual') return 'Controlled';
                }

                // Reduced but still present: suppression, not terminal control.
                if (prev !== null && prev > 0 && current !== null && current > 0 && current < prev && lower !== 'regrowth') {
                    next = 'Suppressed';
                    lower = 'suppressed';
                }

                // Stable non-zero cover should not be reported as terminal control.
                if (prev !== null && current !== null && current > 0 && Math.abs(current - prev) <= 0.1 &&
                    (lower === 'controlled' || lower === 'eliminated' || lower === 'top-kill' || lower === 'suppressed')) {
                    next = 'Unaffected';
                    lower = 'unaffected';
                }

                // Lifecycle-safe terminal status mapping.
                if (lower === 'eliminated') {
                    if (bio.lifecycle === 'Perennial') next = (current !== null && current > 0.1) ? 'Suppressed' : 'Top-kill';
                    else if (bio.lifecycle === 'Unknown') next = 'Suppressed';
                    lower = String(next).toLowerCase();
                }

                // "Controlled" cannot mean full control for perennial weeds and cannot coexist with positive cover.
                if (lower === 'controlled') {
                    if (bio.lifecycle === 'Perennial') next = (current !== null && current > 0.1) ? 'Suppressed' : 'Top-kill';
                    else if (current !== null && current > 0) next = 'Suppressed';
                    lower = String(next).toLowerCase();
                }

                // Top-kill cannot coexist with positive surviving cover.
                if (lower === 'top-kill' && current !== null && current > 0.1) {
                    next = 'Suppressed';
                    lower = 'suppressed';
                }

                // Strong regrowth refinement: substantial post-reduction rebound is regrowth, not top-kill.
                if (prev !== null && current !== null && current > 20 && current > (prev + 0.1)) {
                    next = 'Regrowth';
                    lower = 'regrowth';
                }

                // Status/notes consistency: regrowth cannot coexist with dead-only evidence.
                // Exception: if cover clearly rebounded above prior (cover is ground truth over stale notes).
                const noteText = String(notes || '');
                const coverRebound = prev !== null && current !== null && current > (prev + 0.1);
                if (lower === 'regrowth' && deadRx.test(noteText) && !growthRx.test(noteText) && !coverRebound) {
                    next = bio.isPerennial ? 'Top-kill' : 'Controlled';
                }

                return next;
            };